require 'spec_helper'
require 'webmock/rspec'
require 'vcr'

# This dummy module/class emulates the same class provided by the
# sso openid gem. The sso users api gem only uses it to supply the appropriate
# url. All of the sso urls are managed through the Openid gem (so there is a single)
# point to list and maintain them all.
# Instead of requiring that gem in this gem
# to get specs to pass, we just create the module/class
# here with the one method it needs
module SsoOpenid
  class Urls
    def self.identity_users
      OpenStruct.new(fqdn: "https://users-qa.networkforgood.org")
    end

    def self.portal
      OpenStruct.new(fqdn: "http://account-qa.networkforgood.com")
    end
  end
end



require File.expand_path("../dummy/config/environment.rb",  __FILE__)
Rails.backtrace_cleaner.remove_silencers!

#
# Load support files
ENGINE_RAILS_ROOT=File.join(File.dirname(__FILE__), '../')
Dir[File.join(ENGINE_RAILS_ROOT, "spec/support/**/*.rb")].each {|f| require f }

RSpec.configure do |config|
  config.order = "random"
end

# if you need to recreate the cassettes, you need to
# set the appropriate bearer token on the base class

SsoUsersApi::Base.access_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1RdjVzaDZ6ZElvb3l2eHFER2M1c2dOVWdUUSIsImtpZCI6Ik1RdjVzaDZ6ZElvb3l2eHFER2M1c2dOVWdUUSJ9.eyJpc3MiOiJodHRwczovL2lkZW50aXR5LVFBMDUubmZnaHEub3JnIiwiYXVkIjoiaHR0cHM6Ly9pZGVudGl0eS1RQTA1Lm5mZ2hxLm9yZy9yZXNvdXJjZXMiLCJleHAiOjE2NDAyMjg3MTgsIm5iZiI6MTQ4MjQ0MDcxOCwiY2xpZW50X2lkIjoiTmdmVDNzdGlEIiwiY2xpZW50X3BhcnRuZXJfaWQiOiIxMDA4NTMiLCJjbGllbnRfY2FwYWJpbGl0aWVzIjpbIjAiLCIxIiwiMiIsIjMiLCI0IiwiNiIsIjgiLCI5IiwiMTAiLCIxMSIsIjEyIiwiMTMiLCIxNCIsIjE1IiwiMTYiLCIxOCIsIjE5IiwiMjAiLCIyMSJdLCJjbGllbnRfY2FtcGFpZ25DYXBhYmlsaXRpZXMxMTU2NCI6WyIwIiwiMSIsIjUiLCI2IiwiNyIsIjgiLCI5Il0sImNsaWVudF9jYW1wYWlnbkNhcGFiaWxpdGllczEyNzQwIjpbIjAiLCIxIiwiNSIsIjYiLCI3IiwiOCIsIjkiLCIxMCJdLCJjbGllbnRfY2FtcGFpZ25DYXBhYmlsaXRpZXMxMjc0MiI6WyIwIiwiMSIsIjUiLCI2IiwiNyIsIjgiLCI5IiwiMTAiXSwiY2xpZW50X2NhbXBhaWduQ2FwYWJpbGl0aWVzMTI3MzgiOlsiMCIsIjEiLCI1IiwiNiIsIjciLCI4IiwiOSIsIjEwIl0sImNsaWVudF9jYW1wYWlnbkNhcGFiaWxpdGllczEyNzM2IjpbIjAiLCIxIiwiNSIsIjYiLCI3IiwiOCIsIjkiLCIxMCJdLCJjbGllbnRfY2FtcGFpZ25DYXBhYmlsaXRpZXMxMjc0MyI6WyIwIiwiMSIsIjUiLCI2IiwiNyIsIjgiLCI5IiwiMTAiXSwiY2xpZW50X2NhbXBhaWduQ2FwYWJpbGl0aWVzMTI3MzkiOlsiMCIsIjEiLCI1IiwiNiIsIjciLCI4IiwiOSIsIjEwIl0sImNsaWVudF9jYW1wYWlnbkNhcGFiaWxpdGllczEyNzM3IjpbIjAiLCIxIiwiNSIsIjYiLCI3IiwiOCIsIjkiLCIxMCJdLCJjbGllbnRfY2FtcGFpZ25DYXBhYmlsaXRpZXMxMjc0MSI6WyIwIiwiMSIsIjUiLCI2IiwiNyIsIjgiLCI5IiwiMTAiXSwiY2xpZW50X2NhbXBhaWduQ2FwYWJpbGl0aWVzMTI3MzUiOlsiMCIsIjEiLCI1IiwiNiIsIjciLCI4IiwiOSIsIjEwIl0sImNsaWVudF9jYW1wYWlnbkNhcGFiaWxpdGllczEwNDkxIjpbIjAiLCIxIiwiNCIsIjUiLCI2IiwiNyIsIjgiLCI5Il0sImNsaWVudF9jYW1wYWlnbkNhcGFiaWxpdGllczExNjY5IjpbIjAiLCIxIiwiNSIsIjYiLCI3IiwiOCIsIjkiXSwiY2xpZW50X2NhbXBhaWduQ2FwYWJpbGl0aWVzMTI3MjMiOlsiMCIsIjEiLCI1IiwiNiIsIjciLCI4IiwiOSIsIjEwIl0sImNsaWVudF9jYW1wYWlnbkNhcGFiaWxpdGllczExNjUxIjpbIjAiLCIxIiwiNSIsIjYiLCI3IiwiOCIsIjkiXSwic2NvcGUiOlsiZG9uYXRpb24iLCJpZG1nciJdLCJqdGkiOiJjN2I4NjAwMjk4MGIzY2EwYzg1NTMwYmE0ZjIxM2NmMSJ9.TlhgbteLNSzwZtqTfGaDjW1nEkTr-z91iQl79gK4VvXmqcP0FgrzsE1iQ5hL7QoiJikBKaAFqUDJ3IoLKpAcMa3Y9oSTAysHv6TbuUV-gkcy5bh2Trh3ORNkcAb_BEWG6VI3VBqqumgM5wdqo9VMReZNptBPhcM1fBHMSZ4afdjZepOCSyCpw-HMq1e4pMmVBh0tIIIs3yOfgz7LrLPWT9GTZjM6C7HsIOAIutgN9RuLH0OtqKkIj5wVayaqYp66M1PA-yv_YzG78ELjfFJ1iJ13pVG3uXMzzSiyBnzng4Zj89s6KaeMVbRwV7erGwEi3vm9MjR1KR5ET3aAisoakQ"

VCR.configure do |config|
  config.cassette_library_dir = "spec/fixtures/vcr_cassettes"
  # config.allow_http_connections_when_no_cassette = true
  config.hook_into :webmock
end

require "sso_users_api"