require 'spec_helper'
require 'webmock/rspec'
require 'vcr'

require File.expand_path("../dummy/config/environment.rb",  __FILE__)
Rails.backtrace_cleaner.remove_silencers!

#
# Load support files
ENGINE_RAILS_ROOT=File.join(File.dirname(__FILE__), '../')
Dir[File.join(ENGINE_RAILS_ROOT, "spec/support/**/*.rb")].each {|f| require f }

RSpec.configure do |config|
  config.order = "random"
end

# if you need to recreate the cassettes, you need to
# set the appropriate bearer token on the base class

SsoUsersApi::Base.access_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InpXOW4tazFiRU5Wd085RldsSTVUQ00yYzd4MCIsImtpZCI6InpXOW4tazFiRU5Wd085RldsSTVUQ00yYzd4MCJ9.eyJpc3MiOiJodHRwczovL2lkZW50aXR5LXVhdC5uZXR3b3JrZm9yZ29vZC5vcmciLCJhdWQiOiJodHRwczovL2lkZW50aXR5LXVhdC5uZXR3b3JrZm9yZ29vZC5vcmcvcmVzb3VyY2VzIiwiZXhwIjoxNjQ3ODM4NzQ1LCJuYmYiOjE0OTAwNTA3NDUsImNsaWVudF9pZCI6IkchVjNDMFJQNSIsImNsaWVudF9wYXJ0bmVyX2lkIjoiMTAwNDQ4IiwiY2xpZW50X2NhcGFiaWxpdGllcyI6WyI1IiwiNyIsIjgiLCI5IiwiMTAiLCIxMSIsIjEyIiwiMTMiLCIxNSIsIjE3IiwiMTkiLCIyMSJdLCJjbGllbnRfY2FtcGFpZ25DYXBhYmlsaXRpZXMxMTQzMSI6WyIwIiwiMSIsIjUiLCI5Il0sImNsaWVudF9jYW1wYWlnbkNhcGFiaWxpdGllczExNDA3IjpbIjAiLCIxIiwiNSJdLCJjbGllbnRfY2FtcGFpZ25DYXBhYmlsaXRpZXMxMTQxMCI6WyIwIiwiMSIsIjUiLCI5Il0sImNsaWVudF9jYW1wYWlnbkNhcGFiaWxpdGllczExNDA4IjpbIjAiLCIxIiwiNSIsIjkiXSwiY2xpZW50X2NhbXBhaWduQ2FwYWJpbGl0aWVzMTE0MjYiOlsiMCIsIjEiLCI1IiwiOSJdLCJjbGllbnRfY2FtcGFpZ25DYXBhYmlsaXRpZXMxMTQyNSI6WyIwIiwiMSIsIjUiLCI5Il0sImNsaWVudF9jYW1wYWlnbkNhcGFiaWxpdGllczExNDA2IjpbIjAiLCIxIiwiNSIsIjkiXSwiY2xpZW50X2NhbXBhaWduQ2FwYWJpbGl0aWVzMTE0NDIiOlsiMCIsIjEiLCI1IiwiOSJdLCJjbGllbnRfY2FtcGFpZ25DYXBhYmlsaXRpZXMxMTQyMSI6WyIwIiwiMSIsIjUiLCI5Il0sImNsaWVudF9jYW1wYWlnbkNhcGFiaWxpdGllczExNDMyIjpbIjAiLCIxIiwiOSJdLCJjbGllbnRfY2FtcGFpZ25DYXBhYmlsaXRpZXMxMTQyMCI6WyIwIiwiMSIsIjUiLCI5Il0sImNsaWVudF9jYW1wYWlnbkNhcGFiaWxpdGllczExNDA1IjpbIjAiLCIxIiwiNSIsIjkiXSwiY2xpZW50X2NhbXBhaWduQ2FwYWJpbGl0aWVzMTE0MDkiOlsiMCIsIjEiLCI1IiwiOSJdLCJjbGllbnRfY2FtcGFpZ25DYXBhYmlsaXRpZXMxMTQyNyI6WyIwIiwiMSIsIjUiLCI5Il0sImNsaWVudF9jYW1wYWlnbkNhcGFiaWxpdGllczExNDI0IjpbIjAiLCIxIiwiNSIsIjkiXSwiY2xpZW50X2NhbXBhaWduQ2FwYWJpbGl0aWVzMTEzNTYiOlsiMCIsIjEiLCI1IiwiOSJdLCJjbGllbnRfY2FtcGFpZ25DYXBhYmlsaXRpZXMxMTM1NyI6WyIxIiwiNCIsIjUiXSwiY2xpZW50X2NhbXBhaWduQ2FwYWJpbGl0aWVzMTE0MzAiOlsiMCIsIjEiLCI1IiwiOSJdLCJjbGllbnRfY2FtcGFpZ25DYXBhYmlsaXRpZXMxMTM4NyI6WyIwIiwiMSIsIjUiXSwiY2xpZW50X2NhbXBhaWduQ2FwYWJpbGl0aWVzMTEzNTgiOlsiMCIsIjEiLCI1IiwiOSJdLCJjbGllbnRfY2FtcGFpZ25DYXBhYmlsaXRpZXMxMTM2OSI6WyIwIiwiMSIsIjUiLCI5Il0sInNjb3BlIjpbImRvbmF0aW9uIiwiZG9uYXRpb24tcmVwb3J0aW5nIiwiaWRtZ3IiXSwianRpIjoiZWZiNTA2MTMzY2JmYzY5OTRhNGVhODA1MzZmM2Y0OTMifQ.aBECF_7eBNlDeEX9eqECs8RNi53iFZ6Bl9s8PLaBWCKMvAUtCWfcHki7O7cpgMaffdHzeB0qUR5jVrLuethKZZIPSgMOZaVxV64pxDqp7HK5dlAqxTjkd9d5eC6Z8j2ULMsm6a7vvVhqMrAgNmaefp__xEaiAIge84qBadbkygfuqiNAoMCZ5TWYCFYhsF-A4G1O7J1KyHGhAEU3tPP1wXlPLnLhzxDLapPLidma2RTGfdSmWnjYdcNTvJ9fuRNXkfUhounHuV47Z1D2t0pIncT-4NycIYH6E5nF3niTQhXAxR9zc0rVeCA6dHceKdqHhIZWSsnwXXPnh2QpaxcTzw"


VCR.configure do |config|
  config.cassette_library_dir = "spec/fixtures/vcr_cassettes"
  # config.allow_http_connections_when_no_cassette = true
  config.hook_into :webmock
end

require "sso_users_api"